### ISSUE TITLE
Den zweiten Patienten anfordern.

### ISSUE THREAD

**Issue by JanneckLange** [Game-Engineering/imao-backend#5]
**Spieler anlegen** 
{"vorname":"Max","nachname":"Mustermann"}

**neue Runde erstellen** 
{"budget":1000,"nachricht":"Runde 1 wurde gestartet.","ruf":0,"runde":1,"wartendePatienten":3}

**Patient anfordern** 
{"vorname":"Ibrahim","nachname":"Awolowo","alter":20,"erscheinungID":10,"ID":1}

**_Patient anfordern_**

**type** Exception report

**message** Internal Server Error

**description** The server encountered an internal error that prevented it from fulfilling this request.

**exception**
javax.servlet.ServletException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by JanneckLange** [comment]
Wird vielleicht nur ein Patient erstellt?
Bei neuer Runde wird gesagt -> "wartendePatienten":3

**Comment by FriederikeHerbold** [comment]
ich seh es mir an, wahrscheinlich stimmt was mit den counter nicht

**Comment by JanneckLange** [comment]
**Server Log:**

  StandardWrapperValve[de.hsmannheim.ss18.gae.imao.Server]: Servlet.service() for servlet de.hsmannheim.ss18.gae.imao.Server threw exception
java.lang.**IndexOutOfBoundsException**: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at de.hsmannheim.ss18.gae.imao.model.Spielrunde.getPatient(**Spielrunde.java:96**)
	at de.hsmannheim.ss18.gae.imao.endpunkt.Spiel.getPatatient(Spiel.java:93)
...

_Spielrunde.java_
```
94	public Patient getPatient() {
95		Patient pat = null;
96		if (wartendePatienten.get(0) != null) {
97			pat = wartendePatienten.get(0);
98			wartendePatienten.remove(0);
99			inZelt = pat;
100		}
101		return pat;
102	}
```

**Comment by FriederikeHerbold** [comment]
Behoben
